//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuka.Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yuka.Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Closing archive &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string IO_ArchiveClosing {
            get {
                return ResourceManager.GetString("IO_ArchiveClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to load archive: [{0}] {1} ähnelt.
        /// </summary>
        internal static string IO_ArchiveLoadFailed {
            get {
                return ResourceManager.GetString("IO_ArchiveLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading archive &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string IO_ArchiveLoading {
            get {
                return ResourceManager.GetString("IO_ArchiveLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Archive selection aborted by user ähnelt.
        /// </summary>
        internal static string IO_ArchiveSelectionAbortedByUser {
            get {
                return ResourceManager.GetString("IO_ArchiveSelectionAbortedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Archive file selected: &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string IO_ArchiveSelectionEnded {
            get {
                return ResourceManager.GetString("IO_ArchiveSelectionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selecting archive file... ähnelt.
        /// </summary>
        internal static string IO_ArchiveSelectionStarted {
            get {
                return ResourceManager.GetString("IO_ArchiveSelectionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to perform drag&apos;n drop operation: [{0}] {1} ähnelt.
        /// </summary>
        internal static string IO_DragNDropReceiveFailed {
            get {
                return ResourceManager.GetString("IO_DragNDropReceiveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to export entire archive: [{0}] {1} ähnelt.
        /// </summary>
        internal static string IO_ExportAllFailed {
            get {
                return ResourceManager.GetString("IO_ExportAllFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export folder selected: &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string IO_ExportFolderSelectionEnded {
            get {
                return ResourceManager.GetString("IO_ExportFolderSelectionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selecting folder for archive export... ähnelt.
        /// </summary>
        internal static string IO_ExportFolderSelectionStarted {
            get {
                return ResourceManager.GetString("IO_ExportFolderSelectionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export aborted by user ähnelt.
        /// </summary>
        internal static string IO_FolderSelectionAbortedByUser {
            get {
                return ResourceManager.GetString("IO_FolderSelectionAbortedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to import file: [{0}] {1} ähnelt.
        /// </summary>
        internal static string IO_ImportFileFailed {
            get {
                return ResourceManager.GetString("IO_ImportFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imported file &apos;{0}&apos; to &apos;{1}&apos; ähnelt.
        /// </summary>
        internal static string IO_ImportFileFinished {
            get {
                return ResourceManager.GetString("IO_ImportFileFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to import file &apos;{0}&apos;: File not found ähnelt.
        /// </summary>
        internal static string IO_ImportFileNotFound {
            get {
                return ResourceManager.GetString("IO_ImportFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to import folder: [{0}] {1} ähnelt.
        /// </summary>
        internal static string IO_ImportFolderFailed {
            get {
                return ResourceManager.GetString("IO_ImportFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imported {0} files from &apos;{1}&apos; to &apos;{2}&apos; ähnelt.
        /// </summary>
        internal static string IO_ImportFolderFinished {
            get {
                return ResourceManager.GetString("IO_ImportFolderFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chache miss; loading icon &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string System_IconLoadCacheMiss {
            get {
                return ResourceManager.GetString("System_IconLoadCacheMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log cleared ähnelt.
        /// </summary>
        internal static string System_LogCleared {
            get {
                return ResourceManager.GetString("System_LogCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to open log file: [{0}] {1} ähnelt.
        /// </summary>
        internal static string System_LogFileCannotBeOpened {
            get {
                return ResourceManager.GetString("System_LogFileCannotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Started logging session ähnelt.
        /// </summary>
        internal static string System_LoggingSessionStarted {
            get {
                return ResourceManager.GetString("System_LoggingSessionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        internal static string Tag_General {
            get {
                return ResourceManager.GetString("Tag_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IO ähnelt.
        /// </summary>
        internal static string Tag_IO {
            get {
                return ResourceManager.GetString("Tag_IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logger ähnelt.
        /// </summary>
        internal static string Tag_System {
            get {
                return ResourceManager.GetString("Tag_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UI ähnelt.
        /// </summary>
        internal static string Tag_UI {
            get {
                return ResourceManager.GetString("Tag_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yuka container (*.ykc)|*.ykc|All files (*.*)|*.* ähnelt.
        /// </summary>
        internal static string UI_ArchiveFilter {
            get {
                return ResourceManager.GetString("UI_ArchiveFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are about to export into an existing folder. Continue? ähnelt.
        /// </summary>
        internal static string UI_Confirmation_ExportIntoNonEmptyFolder_Message {
            get {
                return ResourceManager.GetString("UI_Confirmation_ExportIntoNonEmptyFolder_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm action ähnelt.
        /// </summary>
        internal static string UI_ConfirmationDefaultWindowTitle {
            get {
                return ResourceManager.GetString("UI_ConfirmationDefaultWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remember selection ähnelt.
        /// </summary>
        internal static string UI_ConfirmationRememberSelection {
            get {
                return ResourceManager.GetString("UI_ConfirmationRememberSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remembered selection &apos;{0}&apos; for confirmation &apos;{1}&apos; ähnelt.
        /// </summary>
        internal static string UI_ConfirmationUsingRememberedValue {
            get {
                return ResourceManager.GetString("UI_ConfirmationUsingRememberedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deleting preview because &apos;{0}&apos; was deselected ähnelt.
        /// </summary>
        internal static string UI_DeletingPreviewOnDeselect {
            get {
                return ResourceManager.GetString("UI_DeletingPreviewOnDeselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File too long for hex preview ähnelt.
        /// </summary>
        internal static string UI_FileTooLongForHexPreview {
            get {
                return ResourceManager.GetString("UI_FileTooLongForHexPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select an archive file ähnelt.
        /// </summary>
        internal static string UI_OpenArchiveDialogTitle {
            get {
                return ResourceManager.GetString("UI_OpenArchiveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to generate preview: [{0}] {1} ähnelt.
        /// </summary>
        internal static string UI_PreviewFailed {
            get {
                return ResourceManager.GetString("UI_PreviewFailed", resourceCulture);
            }
        }
    }
}
